### ISSUE TITLE
data and readme file

### ISSUE THREAD

**Issue by dshizuka** [BIOS967/BIOS967_Uddin#1]
Hi Main, I have looked at your data and readme files. 
A few comments:
- For the Immune reconstitution data, make sure you include the information that is in the "note" on line 20 in the readme file. Then, you should get rid of that note from the excel sheet. Otherwise, it will cause errors when reading it into R. 
- For the HIV Viral Load data, the current format is not going to be readable for R. What I would do is either reformat it to mirror the Immune reconstitution data, or either add this plasma viral data into the immune constitution data.

**Comment by mainuddin207** [comment]
Thanks for your suggestions. I resolved the comment 1. Would you please take action for comment 2?
